import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Montserrat } from "next/font/google";
import { Suspense } from "react";
import Loading from "@/components/Others/Loading";
import { Toaster } from "sonner";
import { GoogleOAuthProvider } from "@react-oauth/google";
import StoreProvider from "@/redux/StoreProvider";
import GoogleTranslateProvider from "@/components/googleTranslation/GoogleLang";

export const metadata: Metadata = {
  title: "Labis-Engineer 7",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // optional weights
  variable: "--font-montserrat", // optional CSS variable name
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-montserrart relative! z-20 top-0!`}
        suppressHydrationWarning={true}
      >
        <Toaster position="top-center" expand={true} richColors />
        <StoreProvider>
          <GoogleTranslateProvider>
            <GoogleOAuthProvider clientId="68253939211-2ah4drkmkhl74kjqe5tlpks4jk64f50h.apps.googleusercontent.com">
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </GoogleOAuthProvider>
          </GoogleTranslateProvider>
        </StoreProvider>
      </body>
      {/* Screenshot detection script */}
      {/* <Script id="detect-screenshot" strategy="afterInteractive">
        {`
            document.addEventListener("keyup", function(e) {
              if (e.key === "PrintScreen") {
        //           const el = document.getElementById("secret");
        // if (el) {
        //   el.style.backgroundColor = "black";
        // }
        console.log("User taking screenSHot")
                alert("Screenshot attempt detected!");
                navigator.clipboard.writeText("");
              }
            });
          `}
      </Script> */}
    </html>
  );
}
