import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { openSans } from "@/fonts/fonts";
import { Suspense } from "react";
import Loading from "@/components/Others/Loading";
import { Toaster } from "sonner";
import { GoogleOAuthProvider } from "@react-oauth/google";
import StoreProvider from "@/redux/StoreProvider";
import GoogleTranslateProvider from "@/components/googleTranslation/GoogleLang";

export const metadata: Metadata = {
  title: "Labis-Engineer 7",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} relative! z-20 top-0!`} suppressHydrationWarning={true}>
        <Toaster position="top-center" expand={true} richColors />
        <StoreProvider>
          <GoogleTranslateProvider>
            <GoogleOAuthProvider clientId="68253939211-2ah4drkmkhl74kjqe5tlpks4jk64f50h.apps.googleusercontent.com">
              <Suspense fallback={<Loading />}>{children}</Suspense>
            </GoogleOAuthProvider>
          </GoogleTranslateProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
