import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { openSans } from "@/fonts/fonts";
import { Suspense } from "react";
import Loading from "@/components/Others/Loading";
import { Toaster } from "sonner";
import StoreProvider from "./StoreProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Labis-Engineer 7",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.variable}>
        <Toaster position="top-center" expand={true} richColors />
        <GoogleOAuthProvider clientId="959795390198-ijbhg4ob84kgulhod8iauk56iu9s779h.apps.googleusercontent.com">
          <StoreProvider>
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </StoreProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
