type Owner = {
    first_name: string | null;
    last_name: string | null;
    father_first_name: string | null;
    father_last_name: string | null;
    mother_first_name: string | null;
    mother_last_name: string | null;
    date_of_birth: string | null;
    place_of_birth: string | null;
    owner_address: string | null;
    address_number: string | null;
    postal_code: string | null;
    city: string | null;
    id_number: string | null;
    tax_identification_number: string | null;
    ownership_percentage_owner: string | null;
    owner_type_ownership: string | null;
};

type TokenUsage = {
    total_used_tokens: number;
};

export type TProjectData = {
    project_descriptions: string[];
    technical_description: string | null;
    technical_description_two: string | null;
    technical_description_three: string | null;
    technical_description_four: string | null;
    technical_description_five: string | null;
    technical_description_six: string | null;
    technical_description_seven: string | null;
    technical_description_eight: string | null;
    technical_description_nine: string | null;
    declaration_owner_for_4495_2017: string | null;
    kaek_property: string | null;
    title_area: string | null;
    floor_property: string | null;
    number_property: string | null;
    property_address: string | null;
    property_number: string | null;
    property_place: string | null;
    municipality_community: string | null;
    property_postal_code: string | null;
    horizontal_property_name: string | null;
    horizontal_property_name_two: string | null;
    owners: Owner[];
    plot_area: string | null;
    within_outside_city_plan: string | null;
    permit_number: string | null;
    issuing_authority: string | null;
    legalization_statement_number: string | null;
    electronic_code: string | null;
    engineer_full_name: string | null;
    tee_registration_number: string | null;
    specialty: string | null;
    inclusion_date_legalization: string | null;
    ydom_municipality: string | null;
    ydom: string | null;
    ydom_error: string | null;
    processed_documents: string[];
    processing_status: string | null;
    percentage_co_ownership_parcel: string | null;
    exclusive_use_property: string | null;
    mini_description_horizontal_property: string | null;
    number_establishment_horizontal_ownership: string | null;
    reviews_numbers_establishment_horizontal_ownership: string | null;
    notary_reviews_establishment_horizontal_ownership: string | null;
    license_number_revision: string | null;
    license_number_revision_two: string | null;
    date_issuance_building_permit: string | null;
    details_issuing_authority: string | null;
    date_issue_building_permit_revision: string | null;
    date_issue_building_permit_revision_two: string | null;
    project_title_description_license: string | null;
    completion_declaration_3843_number: string | null;
    description_validations_3843: string | null;
    issuing_authority_3843: string | null;
    date_issue_completion_declaration_3843: string | null;
    token_usage: TokenUsage;
    license_number_eemk: string | null;
    date_of_issuance_eemk: string | null;
    issuing_authority_eemk: string | null;
    project_title_description_eemk: string | null;
    license_number_revision_eemk: string | null;
    date_of_issue_building_permit_revision_eemk: string | null;
    issuing_authority_loss_certificate: string | null;
    protocol_number_loss_certificate: string | null;
    protocol_date_loss_certificate: string | null;
    pea_issue_date: string | null;
    pea_security_number: string | null;
    pea_protocol_number: string | null;
    pea_estimated_annual_primary_energy_consumption_kwh_m2: string | null;
    pea_estimated_annual_co2_emissions_kg_m2: string | null;
    declaration_number_1337: string | null;
    issuing_authority_1337: string | null;
    notary_establishment_horizontal_ownership: string | null;
    date_of_submission_1337: string | null;
    project_description_htk_plot: string | null;
    kaek_plot: string | null;
    plot_type: string | null;
};


export type AiOwnerTypes = {
    first_name: string;
    last_name: string;
    father_first__last_name: string;
    mother_first__last_name: string | null;
    date_of_birth: string;
    place_of_birth: string;
    owner_address: string;
    address_number: string;
    postal_code: string;
    city: string;
    id_number: string;
    tax_identification_number: string;
    ownership_percentage_owner: string;
    owner_type_ownership: string;
};

export type OwnerTypes = {
    firstName: string;
    lastName: string;
    fatherFirstLastName: string;
    motherFirstLastName: string | null;
    dateOfBirth: string;
    placeOfBirth: string;
    ownerAddress: string;
    addressNumber: string;
    postalCode: string;
    city: string;
    idNumber: string;
    taxIdentificationNumber: string;
    ownershipPercentageOwner?: string;
    ownerTypeOwnership?: string;
    email: string;
    phone: string;
};